_wandb:
    value:
        cli_version: 0.21.4
        e:
            4fjbbnkzoxxip1amad2ecr8uzis3ibqz:
                args:
                    - --model-config
                    - model_config.yaml
                    - --train-config
                    - train_config.yaml
                    - --wandb-project
                    - cw2_part1_small
                codePath: part1/train.py
                codePathLocal: train.py
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "42267643904"
                email: nimijithwr@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 855efaf564cdd7a3332823891c76db011bcd69b1
                    remote: https://github.com/NIMIJITHNJ/cw2_2025_2026-students.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-f5fdba70-c655-726a-2e62-456285dd606a
                host: da7bf1ab9156
                memory:
                    total: "13605851136"
                os: Linux-6.6.105+-x86_64-with-glibc2.35
                program: /content/cw2_2025_2026-students/part1/train.py
                python: CPython 3.12.12
                root: /content/cw2_2025_2026-students/part1
                startedAt: "2025-11-17T02:25:33.978456Z"
                writerId: 4fjbbnkzoxxip1amad2ecr8uzis3ibqz
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.12
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
dev_batch_size:
    value: 128
dropout_rate:
    value: 0.2
embed_size:
    value: 128
hidden_size:
    value: 128
log_every:
    value: 10
lr:
    value: 0.001
lr_decay:
    value: 0.5
max_epoch:
    value: 30
max_num_trial:
    value: 5
patience:
    value: 1
seed:
    value: 0
train_batch_size:
    value: 32
uniform_init:
    value: 0.1
valid_niter:
    value: 2000
